name: Rollback

on:
  # Allow manual rollback
  workflow_dispatch:
    inputs:
      version:
        description: Specify the semantic version to rollback to, in the format "v*.*.*" (e.g., "v0.0.1")
        type: string
        required: true

jobs:
  check-semantic-version:
    name: check-semantic-version
    uses: ./.github/workflows/wc-check-semantic-version.yml
    with:
      ecr-repository: ${{ vars.PROJECT }}
      version: ${{ inputs.version }}

  # rollback:
  #   name: Rollback
  #   needs: [check-semantic-version]
  #   uses: ./.github/workflows/wc-deploy.yml
  #   with:
  #     rollback: true
  #     aws-region: ${{ vars.AWS_REGION }}
  #     role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
  #     ecr-repository: ${{ vars.PROJECT }}
  #     image-tag: ${{ inputs.version }}
  #     task-definition: ${{ vars.PROJECT }}
  #     container-name: ${{ vars.PROJECT }}
  #     ecs-cluster: ${{ vars.ECS_CLUSTER }}
  #     ecs-service: ${{ vars.PROJECT }}
  #     codedeploy-application: ${{ vars.CODEDEPLOY_APPLICATION }}
  #     codedeploy-application-group: ${{ vars.CODEDEPLOY_APPLICATION_GROUP }}
