name: Update dependency cache

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  update-gradle-cache:
    name: Update dependency cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ vars.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ vars.JAVA_VERSION }}
          distribution: ${{ vars.JAVA_DISTRIBUTION }}

      - uses: actions/cache@v4
        name: Cache dependencies
        id: cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
          lookup-only: true

      - name: Update cache
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          chmod 777 gradlew
          ./gradlew dependencies
